// Standalone migration runner: `pnpm db:migrate`.
// Applies the SQL files generated by `pnpm db:generate` into ./drizzle.
import "./load-env"; // loads .env when run via tsx
import { drizzle } from "drizzle-orm/postgres-js";
import { migrate } from "drizzle-orm/postgres-js/migrator";
import postgres from "postgres";

async function main() {
  const url = process.env.DATABASE_URL ?? "postgres://mlie:mlie@localhost:5433/mlie";
  const client = postgres(url, { max: 1 });
  const db = drizzle(client);

  console.log("Running migrations…");
  await migrate(db, { migrationsFolder: "./drizzle" });
  console.log("Migrations complete.");

  await client.end();
}

main().catch((err) => {
  console.error("Migration failed:", err);
  process.exit(1);
});
